#!/usr/bin/env bash
# Setting up hostname in nginx headers
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "46i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
