#!/usr/bin/env bash
# Installing and configuring HAproxy load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
echo -e "
frontend http_front
\t\tbind *:80
\t\tdefault_backend http_back
backend http_back
\t\tbalance roundrobin
\t\tserver 2609-web-01 34.74.183.76:80 check
\t\tserver 2609-web-02 104.196.154.89:80   check
" | sudo tee /etc/haproxy/haproxy.cfg
service haproxy start