#!/usr/bin/env bash
# Installing and configuring HAproxy load balancer
sudo apt-get -y update
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get install -y haproxy=1.8.\*
FRONTEND="frontend 2907-lb-01\n\tbind *:80\n\tdefault_backend nginx_pool\n"
BACKEND="backend nginx_pool\n\tbalance roundrobin\n\tmode http\n\tserver 2907-web-01 54.159.15.17:80 check\n\tserver 2907-web-02 35.229.123.200:80 check\n"
sudo echo -e $FRONTEND >> /etc/haproxy/haproxy.cfg
sudo echo -e $BACKEND >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
