#!/usr/bin/env bash
#Script demonstrating use of case in while loop
i=1
END=20
while [ $i -le $END ]
do
	echo $i
	case $i in 
		4)
			echo "bad luck from China";;
		9)
			echo "bad luck from Japan";;
		17)
			echo "bad luck from Italy";;
	esac
	((i++))
done
